name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
        CONTAINER_REPOSITORY: ${{ secrets.CONTAINER_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Login to container registry
        docker login kcr.io \
          --username ${{ secrets.CONTAINER_LOGIN }} \
          --password ${{ secrets.API_KEY }}
        # Build a docker container and push it to ECR 
        docker build -t weevolve \
          --build-arg db_user=${{ secrets.DB_USER }} \
          --build-arg db_password=${{ secrets.DB_PASSWORD }} \
          .
        docker tag weevolve:latest $CONTAINER_REPOSITORY:latest
        docker tag weevolve:latest $CONTAINER_REPOSITORY:$IMAGE_TAG
        docker push $CONTAINER_REPOSITORY:latest
        docker push $CONTAINER_REPOSITORY:$IMAGE_TAG

#    - name: Pull and redeploy docker container
#      id: deploy-image
#      uses: appleboy/ssh-action@v0.1.6
#      with:
#        host: ${{ secrets.HOST }}
#        username: ubuntu
#        key: ${{ secrets.ACTION_PRIVATE_KEY }} -- TODO
#        env:
#          CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
#          CONTAINER_REPOSITORY: ${{ secrets.CONTAINER_REPOSITORY }}
#        script: |
#          docker pull $CONTAINER_REPOSITORY:latest
#          docker stop webserver
#          docker rm webserver
#          docker run --name webserver -p 3000:3000 -d $CONTAINER_REPOSITORY:latest
#          docker ps
