name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: kcr.io
        username: ${{ secrets.CONTAINER_LOGIN }}
        password: ${{ secrets.API_KEY }}

    - name: Docker Build and Push
      env:
        CONTAINER_NAME: ${{ github.event.repository.name }}
        CONTAINER_REPOSITORY: ${{ secrets.CONTAINER_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $CONTAINER_NAME \
          --build-arg db_auth=${{ secrets.DB_AUTH }} \
          .
        docker tag $CONTAINER_NAME:latest $CONTAINER_REPOSITORY:latest
        docker tag $CONTAINER_NAME:latest $CONTAINER_REPOSITORY:$IMAGE_TAG
        docker push $CONTAINER_REPOSITORY:latest
        docker push $CONTAINER_REPOSITORY:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Pull and redeploy docker container
      id: deploy-image
      uses: appleboy/ssh-action@v1.2.2
      env:
        CONTAINER_NAME: ${{ github.event.repository.name }}
        CONTAINER_REPOSITORY: ${{ secrets.CONTAINER_REPOSITORY }}
        CONTAINER_LOGIN: ${{ secrets.CONTAINER_LOGIN }}
        API_KEY: ${{ secrets.API_KEY }}
      with:
        host: ${{ secrets.HOST }}
        key: ${{ secrets.PRIVATE_KEY }}
        username: ${{ secrets.HOST_LOGIN }}
        envs: CONTAINER_NAME,CONTAINER_REPOSITORY,CONTAINER_LOGIN,API_KEY
        script: |
          docker login kcr.io --username $CONTAINER_LOGIN --password $API_KEY
          docker pull $CONTAINER_REPOSITORY:latest
          docker stop $CONTAINER_NAME
          docker rm $CONTAINER_NAME
          docker run --name $CONTAINER_NAME -p 3002:3000 --restart unless-stopped -d $CONTAINER_REPOSITORY:latest
